### ISSUE TITLE
Adding support for wp >= 3.0 ?

### ISSUE THREAD

**Issue by matteoredaelli** [diso/wordpress-openid#1]
It seems this plugin does not support the latest releases of wordpress...

**Comment by strk** [comment]
Does supporting 4.4.2 need any further tweak ? Any release planned to include that ?

**Comment by willnorris** [comment]
I had started to do a "final" release a week or two ago and then didn't finish it :disappointed:.  I don't know if there are any changes needed for compatibility with WordPress 4.4.2, as I don't actually use this plugin myself anymore (so uh... you tell me :smile:) .  For all intents and purposes, this plugin is effectively abandoned unless someone wants to take it over.

**Comment by strk** [comment]
Did you find any other plugin effectively allowing use of OpenID for
authenticated comment authors ?

I'm disappointed by the lack of OpenID support in wordpress :(

**Comment by willnorris** [comment]
No, I [migrated off WordPress](https://willnorris.com/2014/07/one-step-forward-two-steps-back) entirely :)

**Comment by strk** [comment]
Uhm, and doing so you gave up the ability for users to leave "comments",
right ?

**Comment by pfefferle** [comment]
@willnorris It would be very sad to abandon the plugin! Let me know if I can help you in any way!

**Comment by strk** [comment]
"Blessing" a new maintainer would be very useful, assuming candidates exist. There are indeed many many forks of the code already.

**Comment by willnorris** [comment]
@strk: Yes, I've decided to just remove comments altogether from my site.  I still receive and store [webmentions](http://indiewebcamp.com/webmention), but don't currently render them.

@pfefferle: but it already is abandoned in all but name.  The last commit here was in Jan 2014 and the last update in the WordPress directory was Nov 2012.  Happy to add you as an admin if you want to maintain it like you have some of my other plugins.

**Comment by willnorris** [comment]
okay @pfefferle, added you both here and in the WordPress directory.

**Comment by strk** [comment]
Thank you, @pfefferle ! I'd like to write a blog post about OpenID and it would not be nice to not allow OpenID comments on it :)

**Comment by pfefferle** [comment]
@willnorris what had you planend to do for your "final" release? do you have any open commits?

**Comment by pfefferle** [comment]
So... I removed a lot of PHP warnings and errors... enough for today...

**Comment by willnorris** [comment]
@pfefferle I didn't have any pending commits... was just going to ship all the commits that have gone in since the last release (https://github.com/diso/wordpress-openid/compare/v3.3.4...master).  It's mostly small stuff, but the update of of the php-openid library does include at least one security fix.

**Comment by strk** [comment]
I'm getting this error on an up-to-date wordpress instance:

[OpenID] Library Error 8192: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in .../wp-content/plugins/openid/lib/Auth/Yadis/ParseHTML.php :86

Should I file another ticket on this repo @pfefferle ? Or are you planning to move the code to a more official group ?

**Comment by pfefferle** [comment]
This seems to be fixed with that commit https://github.com/openid/php-openid/commit/b60f7550d2d8b9fe1d86ba9029a89b7e8a150817#diff-a038a3b1d22f72b51f4b63817575890b and will be fixed with the next release of this plugin, because @willnorris updated the libs a while ago.

**Comment by strk** [comment]
Is there an ETA for next release ?

**Comment by pfefferle** [comment]
I released a new version (3.4.0). I tested it with WordPress 4.3 and it seems to work without any PHP warnings/errors. Let me know if you find some problems, I missed.

**Comment by strk** [comment]
Updated, thanks!
