### ISSUE TITLE
Associating with my profile fails with "OpenID login failed : Invalid openid.mode No mode set"

### ISSUE THREAD

**Issue by mbunkus** [diso/wordpress-openid#12]
First: this is not the same issue as mentioned in the FAQ. I don't run Apache but nginx, hence no mod_security involved at all.

The actual error message is "OpenIDloginfailed:Invalidopenid.modeNomodeset" -- yes, it does not include a single space (as can be seen in the URL).

Setup: nginx 1.0.5, proxying with the FastCGI protocol to php-fpm 5.3.6 on a Ubuntu 11.10 64bit machine. Wordpress 3.3.1, OpenID plugin 3.3.3

This happens with several different OpenID providers, e.g. myopenid.com, pip.verisign-labs.com. In fact I cannot get one of the five I use to work.

Happens both with http and https based OpenIDs.

**Comment by pfefferle** [comment]
Should be fixed with the next major release
