### ISSUE TITLE
Any chance of addressing "This is an OpenID server"?

### ISSUE THREAD

**Issue by AlexHarrowell** [diso/wordpress-openid#47]
Steps to reproduce: Attempt OpenID authentication with any OpenID consuming website.

Expected result: OpenID authentication.

Actual result: Browser redirected to example.com/wordpress/?openid=server, which returns a blank page. Refreshing the page returns a message: This is an OpenID Server. 

This is not useful.

This has been the case for some years now and I read that it is something to do with PHP versions > 5.3. It would be really useful if someone could bring OpenID for WP back to life by updating the version in the WordPress plugin registry!

**Comment by AlexHarrowell** [comment]
There is a patch for this....from 2009: http://patchlog.com/wordpress/openid-server-on-php-5-3/

**Comment by pfefferle** [comment]
what version of PHP are you using? I never ran into this kind of problem.

**Comment by AlexHarrowell** [comment]
5.3.10-1ubuntu3.24

**Comment by pfefferle** [comment]
OK, two things:

* It seems to work fine with actual PHP versions and PHP 5.3 is really old and "End of life" since at least two years
* This is a change in the [lib](https://github.com/openid/php-openid/), this plugin uses, so please try to fix it in the lib, otherwise it might be replaced, in one of the next updates

**Comment by AlexHarrowell** [comment]
Thanks for the quick update - it's now returning "no mode value in
payload". That said the solution is probably to upgrade PHP

**Comment by pfefferle** [comment]
so I close this for now.

**Comment by pfefferle** [comment]
please reopen if problem still exists
