### ISSUE TITLE
Fails to find link attributes in HTML with uppercase HEAD tags

### ISSUE THREAD

**Issue by strk** [diso/wordpress-openid#48]
The plugin does not let you login via an OpenID URI using uppercase HEAD tags.
This was already reported upstream where a pull request is waiting to be merged:
https://github.com/openid/php-openid/pull/134

If you have a local copy of the library I could send a PR here as I did for GNUSocial (https://git.gnu.io/gnu/gnu-social/merge_requests/140)

**Comment by strk** [comment]
Upstream patch was merged

**Comment by pfefferle** [comment]
Cool, will add the changes to the plugin and release a new version. Thanks!

**Comment by strk** [comment]
Since you're at it, are you aware of issues with PHP7 ?
We have two installs of this plugin, one running with PHP6 and another
with PHP7. The PHP7 one is unable to discover openid provider info
from my page, while the other is fine. I'm not sure it is related
to this ticket.

\cc @robe2

**Comment by dgw** [comment]
@strk I suspect your non-PHP7 installation is actually PHP5—perhaps PHP5.6 but not PHP6. There was never an official release of PHP6.

**Comment by pfefferle** [comment]
My Blog runs under PHP 7.1 without problems.

**Comment by strk** [comment]
Then I guess it was PHP5, anyway the question remains: are you aware
of issues with PHP7 ? Have you ever considered writing a testsuite
to run for checking ?

**Comment by strk** [comment]
Can it discover OpenID from strk.kbt.io URL ?

**Comment by pfefferle** [comment]
on my blog, the discovery for `strk.kbt.io` works fine.
