### ISSUE TITLE
Browse sources links to a forbidden page

### ISSUE THREAD

**Issue by strk** [diso/wordpress-openid#49]
This page needs to be updated:
https://wordpress.org/plugins/openid/#developers

In particular it has a broken "Browse the source" link pointing at an url which returns Forbidden to me:
https://plugins.trac.wordpress.org/browser/openid/

**Comment by pfefferle** [comment]
https://github.com/openid/php-openid/issues/138#issuecomment-296926605

> This section can't be edited/changed, it is generated by WordPress.org but the SVN is not outdated, only limited. It is the repo we have to use to release new versions.

:)

**Comment by strk** [comment]
Can it be reported upstream ? Where would that be ?

**Comment by pfefferle** [comment]
It is no bug, it is how WordPress defines it!

**Comment by pfefferle** [comment]
if you do not have access, try to create an account on the WordPress trac

**Comment by strk** [comment]
https://plugins.trac.wordpress.org/ is also forbidden, where's the WordPress trac ?
