### ISSUE TITLE
Assertion not able to be verified

### ISSUE THREAD

**Issue by seanking2919** [diso/wordpress-openid#51]
As of recent, I've been trying to login into a Gitea instance with my OpenID from the WordPress OpenID server. However, it's not working and gives me the following error:

Could not verify assertion with provider

A particular query string caught my eye and I didn't know if this is a problem and how it should be solved:

openid.assoc_handle: {HMAC-SHA1}{5e1e4df1}{h+mJgQ==}

**Comment by pfefferle** [comment]
I run some tests with the Gitea test-instance: https://try.gitea.io/ and it works perfect. Maybe it is a problem with the instance you are using or a problem with your WordPress configuration?!?
